FROM alpine:latest
ENV APP_NAME="MyApp" \
    APP_VERSION="1.0.0" \
    APP_DESCRIPTION="This is a multi-line \
environment variable example"
CMD echo "$APP_DESCRIPTION"

#-----------------------------------------------------------

# FROM alpine
# ENV APP_NAME="MyApp" APP_VERSION="1.0.0" 
# CMD echo "Running $APP_NAME version $APP_VERSION"
