FROM ubuntu:latest
RUN apt-get update && apt-get install -y nginx && rm -rf /var/lib/apt/lists/*


#-------------------------------------------------------
# FROM ubuntu:latest
# RUN apt-get update
# RUN apt-get install -y nginx
# RUN rm -rf /var/lib/apt/lists/*

#-------------------------------------------------------
# FROM alpine:latest
# RUN ["/bin/sh", "-c", "apk add --no-cache curl"]

#-------------------------------------------------------
# FROM alpine:latest
# RUN apk add --no-cache curl