version: '3.8'

services:
  web:
    image: python:3.9
    command: python -m http.server 8000
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - redis
      - db
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  db:
    image: postgres:13-alpine
    secrets:
      - db_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    
volumes:
  redis-data:
  postgres-data:

networks:
  app-network:
    driver: bridge

secrets:
  db_password:
    external: true